### ISSUE TITLE
Satdump windows 11 failed to launch

### ISSUE THREAD

**Issue by smokeywolf57** [SatDump/SatDump.Org#16]
[json.exception.parse_error.101]parse error at line 1,column 1 syntex error while pasing value-unexpected end of imput; expected '[','{', or a literal

The above dug stopped installation of satdump 
odd thing is I was able to use Satdump earlier in the day whcih failed to launch when restarted 
I am using windows 11 
kindest regards Dave

**Comment by JVital2013** [comment]
Hello! It sounds like your settings.json file got corrupted. What were you doing when it last worked?

Either way, you need to delete the corrupted file. Delete settings.json from the config folder if you're using the portable version, or %appdata%\satdump\settings.json if you used the installer.

**Comment by smokeywolf57** [comment]
Hi Jason
Thank you for getting back to me.

I downloaded and started using yesterday worked absolutely fine
Then shut down the laptop and restarted a few hours later .
That's when the error occurred.
I then removed it from windows 11 using settings apps uninstall apps
Rebooted and reinstalled.
The error returned .
I repeated this several times.
Each time the error returned.
I when deleted everything and reloaded on a different partitioned drive .
Still had the same error.
I'm guessing it may be something in the registry that caused the fault but   unfortunately I have no idea how to fix it.
Best Regards
Dave


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JVital2013** [comment]
Have you tried deleting %appdata%\satdump\settings.json?

**Comment by JVital2013** [comment]
In case you aren't used to that nomenclature, %appdata% is a hidden folder. The full path is C:\Username\Appdata\Roaming\satdump\settings.json

**Comment by smokeywolf57** [comment]
I have been clearing the registry with anything associated to SatDump and just seen your latest mail.
It looks like %appdata%\satdump\settings.json has also been deleted.
I will carry on tomorrow and keep you posted.
Your help is appreciated.
Thank you
Best regards
Dave


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JVital2013** [comment]
Thanks for the confirmation. SatDump does not use the registry, other than a few keys with the installer, so it's best to look elsewhere. The registry cannot be causing this problem.

Basically, this error can mean one of two things:

- The overall config file is empty or corrupt, at C:\Program Files\Satdump\share\satdump\satdump_cfg.json.
- The settings.json exists, but the file is empty or corrupt. Note it is fine for this file to be missing.

Neither should ever happen, but here we are - so we need to figure out which it is.

Can you verify that C:\Program Files\Satdump\share\satdump\satdump_cfg.json exists and has data in it? If so - and it probably is - then it's trying to load settings.json from somewhere and you need to figure out where that is.

One troubleshooting step you can do is to open a command prompt, and `cd "C:\Program Files\SatDump\bin"`. Then, run `satdump noaa_apt test test test`. This will log exactly which file is failing to load.

**Comment by smokeywolf57** [comment]
[cid:4a92487c-4a6f-4cda-8aca-e99c14476d7f]




________________________________

**Comment by JVital2013** [comment]
It looks like you tried to send a photo, which doesn't often work over email. Can you attach the photo directly to this issue on GitHub?

Sorry, but thanks!

**Comment by smokeywolf57** [comment]
Hi Jamie
After checking as much as I could I decided to reset my laptop then reloaded SatDump it's now opens I am in the process of setting everything up.
When I have selected a Satellite the frequency doesn't automatically up date .
Any Idea what I am doing wrong ?
Best Regards and thanks for your help
Dave

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JVital2013** [comment]
Are you referring to in the "live" section? You need to select it from the drop-down below the processing pipeline options.

![image](https://github.com/user-attachments/assets/16efd386-d2c1-4643-b50d-f1accf2901a1)

**Comment by JVital2013** [comment]
I'm going to close this for now since your original issue has been resolved. If you have further issues, this isn't really the right place to raise them. Please open them on the SatDump GitHub repository here: https://github.com/SatDump/SatDump/issues.

This repo is for our website, and it is not generally checked for issues. it was lucky @Crosswalkersam pointed me your way :-)
